package com.yx360.design.compose

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * Automatically generated file. DO NOT MODIFY
 */
@Immutable
data class DsColor internal constructor(
    val ElevationSunken: Color,
    val ElevationBase: Color,
    val ElevationRisen: Color,
    val ElevationOverlay: Color,
    val ElevationOverlayBlurred: Color,
    val ElevationOverlayModal: Color,
    val SurfaceGeneric: Color,
    val SurfaceGenericHovered: Color,
    val SurfaceGenericPressed: Color,
    val SurfaceGenericMedium: Color,
    val SurfaceGenericMediumHovered: Color,
    val SurfaceGenericMediumPressed: Color,
    val SurfaceGenericAlt: Color,
    val SurfaceDisabled: Color,
    val SurfaceInverse: Color,
    val SurfaceInverseHovered: Color,
    val SurfaceInversePressed: Color,
    val SurfaceStaticLight: Color,
    val SurfaceStaticHeavy: Color,
    val SurfaceFeedbackInfo: Color,
    val SurfaceFeedbackInfoHovered: Color,
    val SurfaceFeedbackInfoPressed: Color,
    val SurfaceFeedbackInfoLight: Color,
    val SurfaceFeedbackSuccess: Color,
    val SurfaceFeedbackSuccessHovered: Color,
    val SurfaceFeedbackSuccessPressed: Color,
    val SurfaceFeedbackSuccessLight: Color,
    val SurfaceFeedbackWarning: Color,
    val SurfaceFeedbackWarningHovered: Color,
    val SurfaceFeedbackWarningPressed: Color,
    val SurfaceFeedbackWarningLight: Color,
    val SurfaceFeedbackDanger: Color,
    val SurfaceFeedbackDangerHovered: Color,
    val SurfaceFeedbackDangerPressed: Color,
    val SurfaceFeedbackDangerLight: Color,
    val SurfaceFeedbackNeutral: Color,
    val SurfaceFeedbackNeutralHovered: Color,
    val SurfaceFeedbackNeutralPressed: Color,
    val SurfaceFeedbackNeutralLight: Color,
    val SurfaceAccent01: Color,
    val SurfaceAccent02: Color,
    val SurfaceAccent03: Color,
    val SurfaceAccent04: Color,
    val SurfaceAccent05: Color,
    val SurfaceAccent06: Color,
    val SurfaceAccent07: Color,
    val SurfaceAccent08: Color,
    val SurfaceAccent09: Color,
    val SurfaceAccent10: Color,
    val SurfaceAccent11: Color,
    val SurfaceAccent12: Color,
    val SurfaceAccent13: Color,
    val SurfaceAccent14: Color,
    val SurfaceAccent15: Color,
    val SurfaceAccent16: Color,
    val SurfaceAccent17: Color,
    val SurfaceAccent18: Color,
    val LineGenericLight: Color,
    val LineGeneric: Color,
    val LineGenericMedium: Color,
    val LineGenericMediumHovered: Color,
    val LineGenericMediumPressed: Color,
    val LineGenericHeavy: Color,
    val LineFeedbackInfo: Color,
    val LineFeedbackGreen: Color,
    val LineFeedbackWarning: Color,
    val LineFeedbackDanger: Color,
    val LineFeedbackNeutral: Color,
    val TextPrimary: Color,
    val TextSecondary: Color,
    val TextTertiary: Color,
    val TextDisabled: Color,
    val TextInverse: Color,
    val TextStaticHeavy: Color,
    val TextStaticLight: Color,
    val TextFeedbackInfo: Color,
    val TextFeedbackSuccess: Color,
    val TextFeedbackWarning: Color,
    val TextFeedbackDanger: Color,
    val TextFeedbackNeutral: Color,
    val TextAccent01: Color,
    val TextAccent02: Color,
    val TextAccent03: Color,
    val TextAccent04: Color,
    val TextAccent05: Color,
    val TextAccent06: Color,
    val TextAccent07: Color,
    val TextAccent08: Color,
    val TextAccent09: Color,
    val TextAccent10: Color,
    val TextAccent11: Color,
    val TextAccent12: Color,
    val TextAccent13: Color,
    val TextAccent14: Color,
    val TextAccent15: Color,
    val TextAccent16: Color,
    val TextAccent17: Color,
    val MiscShadow: Color,
    val MiscShadowAndroid: Color,
    val TextLetterRead: Color,
    val MiscLineDarkmode: Color,
    val MiscSurfaceMeeting: Color,
    val MiscSkeletonShimmer: Color,
    val MiscGradientYaPlus01: Color,
    val MiscGradientYaPlus02: Color,
    val MiscGradientYaPlus03: Color,
    val MiscGradientFade: Color,
    val Ya360SurfacePrimary: Color,
    val Ya360SurfacePrimaryLight: Color,
    val Ya360SurfaceSecondary: Color,
    val Ya360SurfaceSecondaryLight: Color,
    val Ya360Text: Color,
)

@Immutable
data class DsBrandColor internal constructor(
    val SurfaceBrand: Color,
    val SurfaceBrandHovered: Color,
    val SurfaceBrandPressed: Color,
    val SurfaceBrandLight: Color,
    val SurfaceBrandLightHovered: Color,
    val SurfaceBrandLightPressed: Color,
    val LineBrand: Color,
    val TextBrand: Color,
    val TextBrandStatic: Color,
    val ShadowBrand: Color,
    val TextLink: Color,
    val TextLinkHovered: Color,
    val TextLinkPressed: Color,
    val TextLinkVisited: Color,
)

@Immutable
data class DsUserColor internal constructor(
    val SurfaceUser: Color,
    val SurfaceUserHovered: Color,
    val SurfaceUserPressed: Color,
    val SurfaceUserLight: Color,
    val SurfaceUserLightHovered: Color,
    val SurfaceUserLightPressed: Color,
    val LineUser: Color,
    val LineUserLight: Color,
    val TextUser: Color,
    val TextStaticUser: Color,
)
